### ISSUE TITLE
Create test dataset for MultiPolygon Scenario B

### ISSUE THREAD

**Issue by brittlnv** [iho-ohi/S130PT#3]
In order to represent MultiPolygon geometry in S-130PT (test) datasets, several scenarios are being looked into that solve the MultiPolygon limitations with S-100 Ed. 5.2.0. Currently, the preference is Scenario B. This scenario can be further explored through a test dataset.

![image](https://github.com/user-attachments/assets/d3e1af9a-23bf-4865-920e-dd50d011841b)

**Comment by brittlnv** [comment]
This test dataset is intended to evaluate MultiPolygon solution Scenario B based on two IHO Sea Areas crossing the date line. The provided geometry is for test purposes only and does not influence the final dataset geometry.

https://github.com/iho-ohi/S130PT/blob/main/03_FileCatalogue/13000AASAMPLEDL_110.gml

**Comment by DavidGrant-NIWC** [comment]
|Sample 1|Sample 2|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/0c1ba3d8-14c2-4978-9236-8fea6742fffd)|![image](https://github.com/user-attachments/assets/2c3cc406-5cb5-45e0-a8dd-177e05255897)
