### ISSUE TITLE
S130_SAMPLE.gml uses invalid encoding for `reportedDate`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S130PT#8]
`reportedDate` should probably be a `Date` rather than a `S100_TruncatedDate` (see S-100 5.2 Table 1-2 Data Types). Currently it's defined as a S100_TruncatedDate in the FC. The S100GML schema requires that truncated dates indicate their format as `gDay`, `gMonth`, etc.

Per the S-130 DCEG:
![image](https://github.com/user-attachments/assets/100c2c2c-e5fe-4cab-8367-632118b75989)

The format specifier is missing in S130_SAMPLE.gml:
![image](https://github.com/user-attachments/assets/4f51ea90-9ab1-4de5-bb9a-ed13f8784a8e)

A valid encoding would be:
```
<reportedDate>
  <S100:date>2023-07-05</S100:date>
</reportedDate>
etc.
```

![image](https://github.com/user-attachments/assets/64ec98b1-1a55-457f-bd9c-4f03a4dda3a0)

![image](https://github.com/user-attachments/assets/b62d6fe0-7912-4cc4-8ecc-9c34bd1d4dcf)

**Comment by brittlnv** [comment]
TBD at S-130PT10: for example, source data from IHO only contains information about the year, so in these cases `S100_TruncatedDate` would be a better fit.

**Comment by DavidGrant-NIWC** [comment]
> TBD at S-130PT10: for example, source data from IHO only contains information about the year, so in these cases `S100_TruncatedDate` would be a better fit. Is there a `gYearMonthDay` option for cases where a full date is provided?

In that case the type seems appropriate.
### Encode a specific day
```
<reportedDate>
  <S100:date>2023-07-05</S100:date>
</reportedDate>
```

### Encode a year
```
<reportedDate>
  <S100:gYear>2023</S100:gYear>
</reportedDate>
```
